// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: drivers.sql

package pg

import (
	"context"

	"github.com/google/uuid"
)

const checkCarPlateExists = `-- name: CheckCarPlateExists :one
SELECT EXISTS(
    SELECT 1 FROM drivers 
    WHERE car_plate = $1 AND deleted_at IS NULL AND id != COALESCE($2::uuid, '00000000-0000-0000-0000-000000000000'::uuid)
)
`

type CheckCarPlateExistsParams struct {
	CarPlate string    `json:"car_plate"`
	Column2  uuid.UUID `json:"column_2"`
}

func (q *Queries) CheckCarPlateExists(ctx context.Context, arg CheckCarPlateExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkCarPlateExists, arg.CarPlate, arg.Column2)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const checkLicenseExists = `-- name: CheckLicenseExists :one
SELECT EXISTS(
    SELECT 1 FROM drivers 
    WHERE license_number = $1 AND deleted_at IS NULL AND id != COALESCE($2::uuid, '00000000-0000-0000-0000-000000000000'::uuid)
)
`

type CheckLicenseExistsParams struct {
	LicenseNumber string    `json:"license_number"`
	Column2       uuid.UUID `json:"column_2"`
}

func (q *Queries) CheckLicenseExists(ctx context.Context, arg CheckLicenseExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkLicenseExists, arg.LicenseNumber, arg.Column2)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const checkPhoneExists = `-- name: CheckPhoneExists :one
SELECT EXISTS(
    SELECT 1 FROM drivers 
    WHERE phone = $1 AND deleted_at IS NULL AND id != COALESCE($2::uuid, '00000000-0000-0000-0000-000000000000'::uuid)
)
`

type CheckPhoneExistsParams struct {
	Phone   string    `json:"phone"`
	Column2 uuid.UUID `json:"column_2"`
}

func (q *Queries) CheckPhoneExists(ctx context.Context, arg CheckPhoneExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkPhoneExists, arg.Phone, arg.Column2)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countDrivers = `-- name: CountDrivers :one
SELECT COUNT(*) FROM drivers
WHERE deleted_at IS NULL
AND ($1::text IS NULL OR status = $1)
AND ($2::text IS NULL OR full_name ILIKE '%' || $2 || '%' OR phone ILIKE '%' || $2 || '%')
`

type CountDriversParams struct {
	Column1 string `json:"column_1"`
	Column2 string `json:"column_2"`
}

func (q *Queries) CountDrivers(ctx context.Context, arg CountDriversParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDrivers, arg.Column1, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDriver = `-- name: CreateDriver :one
INSERT INTO drivers (
    full_name,
    phone,
    license_number,
    car_model,
    car_plate,
    status
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, full_name, phone, license_number, car_model, car_plate, status, created_at, updated_at, deleted_at
`

type CreateDriverParams struct {
	FullName      string `json:"full_name"`
	Phone         string `json:"phone"`
	LicenseNumber string `json:"license_number"`
	CarModel      string `json:"car_model"`
	CarPlate      string `json:"car_plate"`
	Status        string `json:"status"`
}

func (q *Queries) CreateDriver(ctx context.Context, arg CreateDriverParams) (Driver, error) {
	row := q.db.QueryRow(ctx, createDriver,
		arg.FullName,
		arg.Phone,
		arg.LicenseNumber,
		arg.CarModel,
		arg.CarPlate,
		arg.Status,
	)
	var i Driver
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Phone,
		&i.LicenseNumber,
		&i.CarModel,
		&i.CarPlate,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getDriverByID = `-- name: GetDriverByID :one
SELECT id, full_name, phone, license_number, car_model, car_plate, status, created_at, updated_at, deleted_at FROM drivers 
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetDriverByID(ctx context.Context, id uuid.UUID) (Driver, error) {
	row := q.db.QueryRow(ctx, getDriverByID, id)
	var i Driver
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Phone,
		&i.LicenseNumber,
		&i.CarModel,
		&i.CarPlate,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getDrivers = `-- name: GetDrivers :many
SELECT id, full_name, phone, license_number, car_model, car_plate, status, created_at, updated_at, deleted_at FROM drivers
WHERE deleted_at IS NULL
AND ($1::text IS NULL OR status = $1)
AND ($2::text IS NULL OR full_name ILIKE '%' || $2 || '%' OR phone ILIKE '%' || $2 || '%')
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type GetDriversParams struct {
	Column1 string `json:"column_1"`
	Column2 string `json:"column_2"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

func (q *Queries) GetDrivers(ctx context.Context, arg GetDriversParams) ([]Driver, error) {
	rows, err := q.db.Query(ctx, getDrivers,
		arg.Column1,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Driver
	for rows.Next() {
		var i Driver
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Phone,
			&i.LicenseNumber,
			&i.CarModel,
			&i.CarPlate,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteDriver = `-- name: SoftDeleteDriver :exec
UPDATE drivers
SET deleted_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteDriver(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteDriver, id)
	return err
}

const updateDriver = `-- name: UpdateDriver :one
UPDATE drivers
SET
    full_name = COALESCE($2, full_name),
    phone = COALESCE($3, phone),
    license_number = COALESCE($4, license_number),
    car_model = COALESCE($5, car_model),
    car_plate = COALESCE($6, car_plate),
    updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, full_name, phone, license_number, car_model, car_plate, status, created_at, updated_at, deleted_at
`

type UpdateDriverParams struct {
	ID            uuid.UUID `json:"id"`
	FullName      string    `json:"full_name"`
	Phone         string    `json:"phone"`
	LicenseNumber string    `json:"license_number"`
	CarModel      string    `json:"car_model"`
	CarPlate      string    `json:"car_plate"`
}

func (q *Queries) UpdateDriver(ctx context.Context, arg UpdateDriverParams) (Driver, error) {
	row := q.db.QueryRow(ctx, updateDriver,
		arg.ID,
		arg.FullName,
		arg.Phone,
		arg.LicenseNumber,
		arg.CarModel,
		arg.CarPlate,
	)
	var i Driver
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Phone,
		&i.LicenseNumber,
		&i.CarModel,
		&i.CarPlate,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateDriverStatus = `-- name: UpdateDriverStatus :one
UPDATE drivers
SET
    status = $2,
    updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, full_name, phone, license_number, car_model, car_plate, status, created_at, updated_at, deleted_at
`

type UpdateDriverStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateDriverStatus(ctx context.Context, arg UpdateDriverStatusParams) (Driver, error) {
	row := q.db.QueryRow(ctx, updateDriverStatus, arg.ID, arg.Status)
	var i Driver
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Phone,
		&i.LicenseNumber,
		&i.CarModel,
		&i.CarPlate,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
