// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: driver_activity.sql

package pg

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getActiveDriversCount = `-- name: GetActiveDriversCount :one
WITH latest_activity AS (
    SELECT DISTINCT ON (driver_id) 
        driver_id,
        action
    FROM driver_activity_log
    ORDER BY driver_id, timestamp DESC
)
SELECT COUNT(*) 
FROM latest_activity 
WHERE action = 'went_online'
`

func (q *Queries) GetActiveDriversCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getActiveDriversCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getDriverActivityLog = `-- name: GetDriverActivityLog :many
SELECT id, driver_id, action, timestamp, notes FROM driver_activity_log
WHERE driver_id = $1
ORDER BY timestamp DESC
LIMIT $2 OFFSET $3
`

type GetDriverActivityLogParams struct {
	DriverID uuid.UUID `json:"driver_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

func (q *Queries) GetDriverActivityLog(ctx context.Context, arg GetDriverActivityLogParams) ([]DriverActivityLog, error) {
	rows, err := q.db.Query(ctx, getDriverActivityLog, arg.DriverID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DriverActivityLog
	for rows.Next() {
		var i DriverActivityLog
		if err := rows.Scan(
			&i.ID,
			&i.DriverID,
			&i.Action,
			&i.Timestamp,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDriverWorkingHours = `-- name: GetDriverWorkingHours :one
WITH activity_pairs AS (
    SELECT 
        driver_id,
        action,
        timestamp,
        LEAD(timestamp) OVER (PARTITION BY driver_id ORDER BY timestamp) as next_timestamp,
        LEAD(action) OVER (PARTITION BY driver_id ORDER BY timestamp) as next_action
    FROM driver_activity_log
    WHERE driver_id = $1
        AND timestamp >= $2
        AND timestamp <= $3
)
SELECT 
    COALESCE(SUM(
        CASE 
            WHEN action = 'went_online' AND next_action = 'went_offline'
            THEN EXTRACT(EPOCH FROM (next_timestamp - timestamp))
            ELSE 0
        END
    ), 0) as total_seconds
FROM activity_pairs
`

type GetDriverWorkingHoursParams struct {
	DriverID    uuid.UUID        `json:"driver_id"`
	Timestamp   pgtype.Timestamp `json:"timestamp"`
	Timestamp_2 pgtype.Timestamp `json:"timestamp_2"`
}

func (q *Queries) GetDriverWorkingHours(ctx context.Context, arg GetDriverWorkingHoursParams) (interface{}, error) {
	row := q.db.QueryRow(ctx, getDriverWorkingHours, arg.DriverID, arg.Timestamp, arg.Timestamp_2)
	var total_seconds interface{}
	err := row.Scan(&total_seconds)
	return total_seconds, err
}

const logDriverActivity = `-- name: LogDriverActivity :one
INSERT INTO driver_activity_log (
    driver_id,
    action,
    notes
) VALUES (
    $1, $2, $3
) RETURNING id, driver_id, action, timestamp, notes
`

type LogDriverActivityParams struct {
	DriverID uuid.UUID `json:"driver_id"`
	Action   string    `json:"action"`
	Notes    *string   `json:"notes"`
}

func (q *Queries) LogDriverActivity(ctx context.Context, arg LogDriverActivityParams) (DriverActivityLog, error) {
	row := q.db.QueryRow(ctx, logDriverActivity, arg.DriverID, arg.Action, arg.Notes)
	var i DriverActivityLog
	err := row.Scan(
		&i.ID,
		&i.DriverID,
		&i.Action,
		&i.Timestamp,
		&i.Notes,
	)
	return i, err
}
