// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package pg

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Driver struct {
	ID            uuid.UUID        `json:"id"`
	FullName      string           `json:"full_name"`
	Phone         string           `json:"phone"`
	LicenseNumber string           `json:"license_number"`
	CarModel      string           `json:"car_model"`
	CarPlate      string           `json:"car_plate"`
	Status        string           `json:"status"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
	DeletedAt     pgtype.Timestamp `json:"deleted_at"`
}

type DriverActivityLog struct {
	ID        uuid.UUID        `json:"id"`
	DriverID  uuid.UUID        `json:"driver_id"`
	Action    string           `json:"action"`
	Timestamp pgtype.Timestamp `json:"timestamp"`
	Notes     *string          `json:"notes"`
}

type User struct {
	ID                      string           `json:"id"`
	GoogleId                *string          `json:"googleId"`
	FullName                *string          `json:"fullName"`
	DateOfBirth             pgtype.Timestamp `json:"dateOfBirth"`
	OverAll                 *int32           `json:"overAll"`
	Level                   *string          `json:"level"`
	Email                   *string          `json:"email"`
	PhoneNumber             *string          `json:"phoneNumber"`
	PasswordHash            *string          `json:"passwordHash"`
	Role                    *string          `json:"role"`
	Gender                  *string          `json:"gender"`
	IsAgreedForUserContract *bool            `json:"isAgreedForUserContract"`
	IsVerified              *bool            `json:"isVerified"`
	Status                  *string          `json:"status"`
	Group                   *string          `json:"group"`
	Photo                   *string          `json:"photo"`
	XP                      *int32           `json:"XP"`
	Balance                 *int64           `json:"balance"`
	FirebaseToken           *string          `json:"firebaseToken"`
	CreatedAt               pgtype.Timestamp `json:"createdAt"`
	UpdatedAt               pgtype.Timestamp `json:"updatedAt"`
	DeletedAt               pgtype.Timestamp `json:"deletedAt"`
}
