// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package pg

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    id,
    "fullName",
    "phoneNumber",
    "passwordHash"
)
VALUES (
    $1, $2, $3, $4
)
RETURNING id, "fullName", "phoneNumber", "passwordHash", "createdAt", "updatedAt", "deletedAt"
`

type CreateUserParams struct {
	ID           string  `json:"id"`
	FullName     *string `json:"fullName"`
	PhoneNumber  *string `json:"phoneNumber"`
	PasswordHash *string `json:"passwordHash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.FullName,
		arg.PhoneNumber,
		arg.PasswordHash,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.PhoneNumber,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT id, "fullName", "phoneNumber", "passwordHash", "createdAt", "updatedAt", "deletedAt" FROM users
`

func (q *Queries) GetAllUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.PhoneNumber,
			&i.PasswordHash,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, "fullName", "phoneNumber", "passwordHash", "createdAt", "updatedAt", "deletedAt" FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.PhoneNumber,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByPhoneNumber = `-- name: GetUserByPhoneNumber :one
SELECT id, "fullName", "phoneNumber", "passwordHash", "createdAt", "updatedAt", "deletedAt" FROM users WHERE "phoneNumber" = $1
`

func (q *Queries) GetUserByPhoneNumber(ctx context.Context, phonenumber *string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByPhoneNumber, phonenumber)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.PhoneNumber,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users SET
    "fullName" = COALESCE($2, "fullName"),
    "phoneNumber" = COALESCE($3, "phoneNumber"),
    "passwordHash" = COALESCE($4, "passwordHash"),
    "updatedAt" = now()
WHERE id = $1
RETURNING id, "fullName", "phoneNumber", "passwordHash", "createdAt", "updatedAt", "deletedAt"
`

type UpdateUserParams struct {
	ID           string  `json:"id"`
	FullName     *string `json:"fullName"`
	PhoneNumber  *string `json:"phoneNumber"`
	PasswordHash *string `json:"passwordHash"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.FullName,
		arg.PhoneNumber,
		arg.PasswordHash,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.PhoneNumber,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
